apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: test
    logging-infra: log-generator
    provider: openshift
  name: log-generator
  namespace: log-generator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: test
      logging-infra: log-generator
      provider: openshift
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: test
        logging-infra: log-generator
        provider: openshift
      name: log-generator
    spec:
      containers:
      - args:
        - sh
        - -c
        - 'i=0; while true; do echo $i: My life is my message; i=$((i+1)) ; sleep
          1; done'
        image: busybox
        imagePullPolicy: Always
        name: log-generator
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

