apiVersion: v1
kind: Service
metadata:
  labels:
    logging-infra: support
  name: fluent-receiver
  namespace: openshift-logging
spec:
  ports:
  - port: 24224
  selector:
    component: fluent-receiver
    provider: openshift

