apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: fluent-receiver
    logging-infra: fluent-receiver
    provider: openshift
  name: fluent-receiver
  namespace: openshift-logging
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: fluent-receiver
      logging-infra: fluent-receiver
      provider: openshift
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: fluent-receiver
        logging-infra: fluent-receiver
        provider: openshift
      name: fluent-receiver
    spec:
      containers:
      - args:
        - fluentd
        - -c
        - /fluentd/etc/fluent.conf
        image: quay.io/openshift/origin-logging-fluentd:latest
        imagePullPolicy: Always
        name: fluent-receiver
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentd/etc
          name: config
          readOnly: true
        - mountPath: /etc/fluentd/secrets
          name: certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluent-receiver
      serviceAccountName: fluent-receiver
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: fluent-receiver
        name: config
      - name: certs
        secret:
          defaultMode: 420
          secretName: fluent-receiver
